Repository girlscript/gssoc-website-new, pull requests merged in 2022-04, with the labels that each got.

#75 added searchbar functionality to Leaderboard
  pages/leaderboard.js
  styles/globals.css
Labels: GSSoC22, Level3

#77 Loader for leaderboard
  package.json
  pages/leaderboard.js
  styles/globals.css
Labels: enhancement, GSSoC22, Level3

#71 feat: live chatbot added
  components/BackToTopButton.js
  components/ChatwootWidget.js
  pages/_app.js
  pages/blog.js
Labels: Level2, GSSoC22

#80 Fixed PR links and added view Button
  pages/leaderboard.js
  styles/globals.css
Labels: GSSoC22, Level3
