Repository girlscript/gssoc-website-new, pull requests merged in 2024-06, with the labels that each got.

#254 Event-page-Update
  pages/api/event_data.js
Labels: level1, gssoc

#261 [Feat]: Enhancement the LeaderBoard searchbar
  pages/leaderboard.js
Labels: level1, gssoc

#265 Event page update
  pages/api/event_data.js
Labels: level1, gssoc

#267 index ui update
  pages/index.js
  styles/globals.css
Labels: level1, gssoc

#272 Enhanced "Scroll-to-Top Button" UI/UX Matching to "Website's Design" Theme
  components/BackToTopButton.js
Labels: level3, gssoc

#274 Winter of Blockchain page in existing Gssoc Website added
  components/Navbar.js
  pages/wob.js
  public/WoB/Ellipse.png
  public/WoB/Group.png
  public/WoB/Hero_Image_Dev_Theme.svg
  public/WoB/Right_Duo.png
  public/WoB/WoB_Schedule_Light_Mode-Dev.png
  public/WoB/graph.png
  public/WoB/people.png
  public/WoB/snow_flower.png
  public/WoB/sponser_bg.png
Labels: level3, gssoc

#275 Implement "Scroll Progress Bar" for Improved User Experience
  components/Layout.js
  components/ScrollProgressBar.js
  styles/globals.css
Labels: level2, gssoc

#284 WOB Projects page development Added
  pages/wobProject.js
  public/WoB/projects_card.png
Labels: level3, gssoc

#286 feat: project page details added
  pages/project.js
Labels: level3, gssoc

#287 WoB Teams page development added
  pages/wobTeam.js
  public/WoB/GithubIcon.png
  public/WoB/LinkedInIcon.png
  public/WoB/TwitterIcon.png
  public/WoB/teamMember.png
Labels: level3, gssoc

#294 Improve Projects Page
  package.json
  pages/project.js
Labels: level3, gssoc

#298 WoB Leaderboard page development. Added
  pages/wobLeaderboard.js
  public/WoB/leaderboard_github.png
  public/WoB/leaderbord_Avatar.png
  public/WoB/top_leads.png
  public/WoB/top_leads1.png
Labels: level3, gssoc

#303 WoB: Main Page: Enhancement Fixed
  pages/wob.js
  public/WoB/WOB_Black.png
  public/WoB/WOB_White.png
Labels: level3, gssoc

#306 WoB: Favicon Updates & Logo Updated.
  pages/wob.js
  pages/wobEvents.js
  pages/wobLeaderboard.js
  pages/wobProject.js
  pages/wobTeam.js
  public/WoB/Favicon.ico
Labels: level2, gssoc

#304 update contact page
  pages/contact.js
Labels: level2, gssoc

#302 Enhanced Pagination Tool
  pages/leaderboard.js
  styles/globals.css
Labels: level3, gssoc
