Repository girlscript/gssoc-website-new, pull requests merged in 2024-05, with the labels that each got.

#237 BUG: Fixed leaderboard bubbling issue
  components/Navbar.js
Labels: level2, gssoc

#242 Done Changing the stats #241
  pages/index.js
Labels: documentation, gssoc

#240 EventpageUpdate
  pages/api/event_data.js
Labels: level1, gssoc

#243 Changing the stats #241
  pages/index.js
Labels: gssoc

#245 Event-page -update
  pages/api/event_data.js
Labels: level1, gssoc

#244 Implemented and set the badges according to some milestones
  package-lock.json
  package.json
  pages/api/leaderboard24.json
  pages/leaderboard.js
  public/badges/1.png
  public/badges/2.png
  public/badges/3.png
  public/badges/4.png
  public/badges/5.png
  public/badges/6.png
  public/badges/7.png
  public/badges/8.png
Labels: level1, gssoc

#248 Modified blacklist contributors
  pages/leaderboard.js
Labels: level1, gssoc

#249 fix: UI bug with badges with score less than 60 #247
  pages/leaderboard.js
Labels: level1, gssoc
